-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 17:51:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbCliente` (
  `idCliente` INT NOT NULL,
  `cliNome` VARCHAR(45) NULL,
  `cliIdentificacao` VARCHAR(45) NULL,
  `cliEndereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPedido` (
  `idPedido` INT NOT NULL,
  `pedDtCompra` DATETIME NULL,
  `pedStatus` VARCHAR(45) NULL,
  `pedVlrCompra` VARCHAR(45) NULL,
  `tbCliente_idCliente` INT NOT NULL,
  `pedVlrFrete` FLOAT NULL,
  PRIMARY KEY (`idPedido`, `tbCliente_idCliente`),
  INDEX `fk_tbPedido_tbCliente1_idx` (`tbCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_tbPedido_tbCliente1`
    FOREIGN KEY (`tbCliente_idCliente`)
    REFERENCES `mydb`.`tbCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbFornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbFornecedor` (
  `idFornecedor` INT NOT NULL,
  `forRazaoSocial` VARCHAR(45) NULL,
  `forCNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbEstoque` (
  `idEstoque` INT NOT NULL,
  `estLocal` VARCHAR(45) NULL,
  `estQtdEstoque` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbProduto` (
  `idProduto` INT NOT NULL,
  `proValor` VARCHAR(45) NULL,
  `proDescricao` VARCHAR(45) NULL,
  `proCategoria` VARCHAR(45) NULL,
  `tbPedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `tbPedido_idPedido`),
  INDEX `fk_tbProduto_tbPedido_idx` (`tbPedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_tbProduto_tbPedido`
    FOREIGN KEY (`tbPedido_idPedido`)
    REFERENCES `mydb`.`tbPedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbVendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbVendedor` (
  `idVendedor` INT NOT NULL,
  `venRazaoSocial` VARCHAR(45) NULL,
  `venEndereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbEstoque_has_tbProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbEstoque_has_tbProduto` (
  `tbProduto_idProduto` INT NOT NULL,
  `tbEstoque_idEstoque` INT NOT NULL,
  `tbProduto_tbEstoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`tbProduto_idProduto`, `tbEstoque_idEstoque`, `tbProduto_tbEstoque_idEstoque`),
  INDEX `fk_tbEstoque_has_tbProduto_tbProduto1_idx` (`tbProduto_idProduto` ASC, `tbProduto_tbEstoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_tbEstoque_has_tbProduto_tbEstoque1_idx` (`tbEstoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_tbEstoque_has_tbProduto_tbEstoque1`
    FOREIGN KEY (`tbEstoque_idEstoque`)
    REFERENCES `mydb`.`tbEstoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEstoque_has_tbProduto_tbProduto1`
    FOREIGN KEY (`tbProduto_idProduto`)
    REFERENCES `mydb`.`tbProduto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbProduto_has_tbFornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbProduto_has_tbFornecedor` (
  `tbProduto_idProduto` INT NOT NULL,
  `tbFornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`tbProduto_idProduto`, `tbFornecedor_idFornecedor`),
  INDEX `fk_tbProduto_has_tbFornecedor_tbFornecedor1_idx` (`tbFornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_tbProduto_has_tbFornecedor_tbProduto1_idx` (`tbProduto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_tbProduto_has_tbFornecedor_tbProduto1`
    FOREIGN KEY (`tbProduto_idProduto`)
    REFERENCES `mydb`.`tbProduto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProduto_has_tbFornecedor_tbFornecedor1`
    FOREIGN KEY (`tbFornecedor_idFornecedor`)
    REFERENCES `mydb`.`tbFornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbProduto_has_tbVendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbProduto_has_tbVendedor` (
  `tbProduto_idProduto` INT NOT NULL,
  `tbVendedor_idVendedor` INT NOT NULL,
  `pvQuantidade` INT NULL,
  PRIMARY KEY (`tbProduto_idProduto`, `tbVendedor_idVendedor`),
  INDEX `fk_tbProduto_has_tbVendedor_tbVendedor1_idx` (`tbVendedor_idVendedor` ASC) VISIBLE,
  INDEX `fk_tbProduto_has_tbVendedor_tbProduto1_idx` (`tbProduto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_tbProduto_has_tbVendedor_tbProduto1`
    FOREIGN KEY (`tbProduto_idProduto`)
    REFERENCES `mydb`.`tbProduto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProduto_has_tbVendedor_tbVendedor1`
    FOREIGN KEY (`tbVendedor_idVendedor`)
    REFERENCES `mydb`.`tbVendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
