-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 23:55:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbVeiculo` (
  `idVeiculo` INT NOT NULL,
  `veiMarca` VARCHAR(45) NULL,
  `veiDescricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbCliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `tbVeiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `tbVeiculo_idVeiculo`),
  INDEX `fk_tbCliente_tbVeiculo1_idx` (`tbVeiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_tbCliente_tbVeiculo1`
    FOREIGN KEY (`tbVeiculo_idVeiculo`)
    REFERENCES `mydb`.`tbVeiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbServico` (
  `idServico` INT NOT NULL,
  `serDescricao` VARCHAR(45) NULL,
  `tbResponsavel_idResponsavel` INT NOT NULL,
  PRIMARY KEY (`idServico`, `tbResponsavel_idResponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbMecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbMecanico` (
  `idMecanico` INT NOT NULL,
  `mecNome` VARCHAR(45) NULL,
  `mecEndereco` VARCHAR(45) NULL,
  `mecEspecialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbExecucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbExecucao` (
  `tbServico_idServico` INT NOT NULL,
  `idExecucao` INT NOT NULL,
  `tbMecanico_idMecanico` INT NOT NULL,
  `exeValorServico` VARCHAR(45) NULL,
  PRIMARY KEY (`tbServico_idServico`, `idExecucao`, `tbMecanico_idMecanico`),
  INDEX `fk_tbServico_has_tbMecanico_tbMecanico1_idx` (`tbMecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_tbServico_has_tbMecanico_tbServico1_idx` (`tbServico_idServico` ASC, `idExecucao` ASC) VISIBLE,
  CONSTRAINT `fk_tbServico_has_tbMecanico_tbServico1`
    FOREIGN KEY (`tbServico_idServico` , `idExecucao`)
    REFERENCES `mydb`.`tbServico` (`idServico` , `tbResponsavel_idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbServico_has_tbMecanico_tbMecanico1`
    FOREIGN KEY (`tbMecanico_idMecanico`)
    REFERENCES `mydb`.`tbMecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPedido` (
  `idPedido` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `responsavel` INT NULL,
  `dtSolicitacao` DATE NULL,
  `tbCliente_idCliente` INT NOT NULL,
  `liberado` TINYINT NULL,
  `tbPedidocol` VARCHAR(45) NULL,
  `tbExecucao_tbServico_idServico` INT NOT NULL,
  `tbExecucao_idExecucao` INT NOT NULL,
  `tbExecucao_tbMecanico_idMecanico` INT NOT NULL,
  `tbCliente_idCliente1` INT NOT NULL,
  `tbCliente_tbVeiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `tbCliente_idCliente`, `tbExecucao_tbServico_idServico`, `tbExecucao_idExecucao`, `tbExecucao_tbMecanico_idMecanico`, `tbCliente_idCliente1`, `tbCliente_tbVeiculo_idVeiculo`),
  INDEX `fk_tbPedido_tbExecucao1_idx` (`tbExecucao_tbServico_idServico` ASC, `tbExecucao_idExecucao` ASC, `tbExecucao_tbMecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_tbPedido_tbCliente1_idx` (`tbCliente_idCliente1` ASC, `tbCliente_tbVeiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_tbPedido_tbExecucao1`
    FOREIGN KEY (`tbExecucao_tbServico_idServico` , `tbExecucao_idExecucao` , `tbExecucao_tbMecanico_idMecanico`)
    REFERENCES `mydb`.`tbExecucao` (`tbServico_idServico` , `idExecucao` , `tbMecanico_idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbPedido_tbCliente1`
    FOREIGN KEY (`tbCliente_idCliente1` , `tbCliente_tbVeiculo_idVeiculo`)
    REFERENCES `mydb`.`tbCliente` (`idCliente` , `tbVeiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbOrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbOrdemServico` (
  `idOrdemServico` INT NOT NULL,
  `osDtEmissao` VARCHAR(45) NULL,
  `osStatus` VARCHAR(45) NULL,
  `osValor` VARCHAR(45) NULL,
  `osDtConclusao` VARCHAR(45) NULL,
  `tbPedido_idPedido` INT NOT NULL,
  `tbPedido_tbCliente_idCliente` INT NOT NULL,
  `tbPedido_tbExecucao_tbServico_idServico` INT NOT NULL,
  `tbPedido_tbExecucao_idExecucao` INT NOT NULL,
  `tbPedido_tbExecucao_tbMecanico_idMecanico` INT NOT NULL,
  `tbPedido_tbCliente_idCliente1` INT NOT NULL,
  `tbPedido_tbCliente_tbVeiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idOrdemServico`, `tbPedido_idPedido`, `tbPedido_tbCliente_idCliente`, `tbPedido_tbExecucao_tbServico_idServico`, `tbPedido_tbExecucao_idExecucao`, `tbPedido_tbExecucao_tbMecanico_idMecanico`, `tbPedido_tbCliente_idCliente1`, `tbPedido_tbCliente_tbVeiculo_idVeiculo`),
  INDEX `fk_tbOrdemServico_tbPedido1_idx` (`tbPedido_idPedido` ASC, `tbPedido_tbCliente_idCliente` ASC, `tbPedido_tbExecucao_tbServico_idServico` ASC, `tbPedido_tbExecucao_idExecucao` ASC, `tbPedido_tbExecucao_tbMecanico_idMecanico` ASC, `tbPedido_tbCliente_idCliente1` ASC, `tbPedido_tbCliente_tbVeiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_tbOrdemServico_tbPedido1`
    FOREIGN KEY (`tbPedido_idPedido` , `tbPedido_tbCliente_idCliente` , `tbPedido_tbExecucao_tbServico_idServico` , `tbPedido_tbExecucao_idExecucao` , `tbPedido_tbExecucao_tbMecanico_idMecanico` , `tbPedido_tbCliente_idCliente1` , `tbPedido_tbCliente_tbVeiculo_idVeiculo`)
    REFERENCES `mydb`.`tbPedido` (`idPedido` , `tbCliente_idCliente` , `tbExecucao_tbServico_idServico` , `tbExecucao_idExecucao` , `tbExecucao_tbMecanico_idMecanico` , `tbCliente_idCliente1` , `tbCliente_tbVeiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
