-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 15:25:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbCliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPedido` (
  `idPedido` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `responsavel` INT NULL,
  `dtSolicitacao` DATE NULL,
  `tbCliente_idCliente` INT NOT NULL,
  `liberado` TINYINT NULL,
  `tbPedidocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`, `tbCliente_idCliente`),
  INDEX `fk_tbPedido_tbCliente_idx` (`tbCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_tbPedido_tbCliente`
    FOREIGN KEY (`tbCliente_idCliente`)
    REFERENCES `mydb`.`tbCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbResponsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbResponsavel` (
  `idResponsavel` INT NOT NULL,
  `none` VARCHAR(45) NULL,
  `lvHelpDesk` INT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbOrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbOrdemServico` (
  `idOrdemServico` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `tbPedido_idPedido` INT NOT NULL,
  `tbPedido_tbCliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdemServico`, `tbPedido_idPedido`, `tbPedido_tbCliente_idCliente`),
  INDEX `fk_tbOrdemServico_tbPedido1_idx` (`tbPedido_idPedido` ASC, `tbPedido_tbCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_tbOrdemServico_tbPedido1`
    FOREIGN KEY (`tbPedido_idPedido` , `tbPedido_tbCliente_idCliente`)
    REFERENCES `mydb`.`tbPedido` (`idPedido` , `tbCliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Analise de Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Analise de Pedido` (
  `tbResponsavel_idResponsavel` INT NOT NULL,
  `tbPedido_idPedido` INT NOT NULL,
  `tbPedido_tbCliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`tbResponsavel_idResponsavel`, `tbPedido_idPedido`, `tbPedido_tbCliente_idCliente`),
  INDEX `fk_tbResponsavel_has_tbPedido_tbPedido1_idx` (`tbPedido_idPedido` ASC, `tbPedido_tbCliente_idCliente` ASC) VISIBLE,
  INDEX `fk_tbResponsavel_has_tbPedido_tbResponsavel1_idx` (`tbResponsavel_idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_tbResponsavel_has_tbPedido_tbResponsavel1`
    FOREIGN KEY (`tbResponsavel_idResponsavel`)
    REFERENCES `mydb`.`tbResponsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbResponsavel_has_tbPedido_tbPedido1`
    FOREIGN KEY (`tbPedido_idPedido` , `tbPedido_tbCliente_idCliente`)
    REFERENCES `mydb`.`tbPedido` (`idPedido` , `tbCliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
