-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 21:11:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPessoa` (
  `idPessoa` INT NOT NULL,
  `pesNome` VARCHAR(45) NULL,
  `pesCPF` VARCHAR(45) NOT NULL,
  `pesEndereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `pesCPF_UNIQUE` (`pesCPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbAlunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbAlunos` (
  `idAlunos` INT NOT NULL,
  `alnMatricula` VARCHAR(45) NOT NULL,
  `tbPessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idAlunos`),
  INDEX `fk_tbAlunos_tbPessoa1_idx` (`tbPessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_tbAlunos_tbPessoa1`
    FOREIGN KEY (`tbPessoa_idPessoa`)
    REFERENCES `mydb`.`tbPessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbDepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDepartamento` (
  `idDepartamento` INT NOT NULL,
  `depNome` VARCHAR(45) NOT NULL,
  `depCampus` VARCHAR(45) NOT NULL,
  `idProfessor_Coordenador` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`, `idProfessor_Coordenador`),
  INDEX `fk_tbDepartamento_tbProfessor1_idx` (`idProfessor_Coordenador` ASC) VISIBLE,
  CONSTRAINT `fk_tbDepartamento_tbProfessor1`
    FOREIGN KEY (`idProfessor_Coordenador`)
    REFERENCES `mydb`.`tbProfessor` (`idtbProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbProfessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbProfessor` (
  `idtbProfessor` INT NOT NULL,
  `tbDepartamento_idDepartamento` INT NOT NULL,
  `tbPessoa_idPessoa` INT NOT NULL,
  `prfRegistro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtbProfessor`, `tbDepartamento_idDepartamento`),
  INDEX `fk_tbProfessor_tbDepartamento1_idx` (`tbDepartamento_idDepartamento` ASC) VISIBLE,
  INDEX `fk_tbProfessor_tbPessoa1_idx` (`tbPessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_tbProfessor_tbDepartamento1`
    FOREIGN KEY (`tbDepartamento_idDepartamento`)
    REFERENCES `mydb`.`tbDepartamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProfessor_tbPessoa1`
    FOREIGN KEY (`tbPessoa_idPessoa`)
    REFERENCES `mydb`.`tbPessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbDisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDisciplina` (
  `idDisciplina` INT NOT NULL,
  `disDescricao` VARCHAR(45) NULL,
  `tbProfessor_idtbProfessor` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`, `tbProfessor_idtbProfessor`),
  INDEX `fk_tbDisciplina_tbProfessor1_idx` (`tbProfessor_idtbProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_tbDisciplina_tbProfessor1`
    FOREIGN KEY (`tbProfessor_idtbProfessor`)
    REFERENCES `mydb`.`tbProfessor` (`idtbProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbCurso` (
  `idCurso` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idDepartamento`),
  INDEX `fk_tbCurso_tbDepartamento1_idx` (`idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_tbCurso_tbDepartamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`tbDepartamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbMatricula` (
  `tbAlunos_idAlunos` INT NOT NULL,
  `tbDisciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`tbAlunos_idAlunos`, `tbDisciplina_idDisciplina`),
  INDEX `fk_tbAlunos_has_tbDisciplina_tbDisciplina1_idx` (`tbDisciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_tbAlunos_has_tbDisciplina_tbAlunos1_idx` (`tbAlunos_idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_tbAlunos_has_tbDisciplina_tbAlunos1`
    FOREIGN KEY (`tbAlunos_idAlunos`)
    REFERENCES `mydb`.`tbAlunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbAlunos_has_tbDisciplina_tbDisciplina1`
    FOREIGN KEY (`tbDisciplina_idDisciplina`)
    REFERENCES `mydb`.`tbDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbDisciplinaCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDisciplinaCurso` (
  `tbDisciplina_idDisciplina` INT NOT NULL,
  `tbCurso_idCurso` INT NOT NULL,
  PRIMARY KEY (`tbDisciplina_idDisciplina`, `tbCurso_idCurso`),
  INDEX `fk_tbDisciplina_has_tbCurso_tbCurso1_idx` (`tbCurso_idCurso` ASC) VISIBLE,
  INDEX `fk_tbDisciplina_has_tbCurso_tbDisciplina1_idx` (`tbDisciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_tbDisciplina_has_tbCurso_tbDisciplina1`
    FOREIGN KEY (`tbDisciplina_idDisciplina`)
    REFERENCES `mydb`.`tbDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDisciplina_has_tbCurso_tbCurso1`
    FOREIGN KEY (`tbCurso_idCurso`)
    REFERENCES `mydb`.`tbCurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPreRequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPreRequisitos` (
  `idPreRequisitos` INT NOT NULL,
  PRIMARY KEY (`idPreRequisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPreRequisitosDiciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPreRequisitosDiciplinas` (
  `tbDisciplina_idDisciplina` INT NOT NULL,
  `tbPreRequisitos_idPreRequisitos` INT NOT NULL,
  PRIMARY KEY (`tbDisciplina_idDisciplina`, `tbPreRequisitos_idPreRequisitos`),
  INDEX `fk_tbPreRequisitosDiciplinas_tbPreRequisitos1_idx` (`tbPreRequisitos_idPreRequisitos` ASC) VISIBLE,
  CONSTRAINT `fk_tbPreRequisitosDiciplinas_tbDisciplina1`
    FOREIGN KEY (`tbDisciplina_idDisciplina`)
    REFERENCES `mydb`.`tbDisciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbPreRequisitosDiciplinas_tbPreRequisitos1`
    FOREIGN KEY (`tbPreRequisitos_idPreRequisitos`)
    REFERENCES `mydb`.`tbPreRequisitos` (`idPreRequisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbPeriodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPeriodo` (
  `idPeriodo` INT NOT NULL,
  `perAno` VARCHAR(45) NULL,
  `perSemestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbOfertaDisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbOfertaDisciplina` (
  `tbPeriodo_idPeriodo` INT NOT NULL,
  `tbDisciplina_idDisciplina` INT NOT NULL,
  `tbDisciplina_tbProfessor_idtbProfessor` INT NOT NULL,
  PRIMARY KEY (`tbPeriodo_idPeriodo`, `tbDisciplina_idDisciplina`, `tbDisciplina_tbProfessor_idtbProfessor`),
  INDEX `fk_tbPeriodo_has_tbDisciplina_tbDisciplina1_idx` (`tbDisciplina_idDisciplina` ASC, `tbDisciplina_tbProfessor_idtbProfessor` ASC) VISIBLE,
  INDEX `fk_tbPeriodo_has_tbDisciplina_tbPeriodo1_idx` (`tbPeriodo_idPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_tbPeriodo_has_tbDisciplina_tbPeriodo1`
    FOREIGN KEY (`tbPeriodo_idPeriodo`)
    REFERENCES `mydb`.`tbPeriodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbPeriodo_has_tbDisciplina_tbDisciplina1`
    FOREIGN KEY (`tbDisciplina_idDisciplina` , `tbDisciplina_tbProfessor_idtbProfessor`)
    REFERENCES `mydb`.`tbDisciplina` (`idDisciplina` , `tbProfessor_idtbProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbAlunos_has_tbCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbAlunos_has_tbCurso` (
  `tbAlunos_idAlunos` INT NOT NULL,
  `tbCurso_idCurso` INT NOT NULL,
  PRIMARY KEY (`tbAlunos_idAlunos`, `tbCurso_idCurso`),
  INDEX `fk_tbAlunos_has_tbCurso_tbCurso1_idx` (`tbCurso_idCurso` ASC) VISIBLE,
  INDEX `fk_tbAlunos_has_tbCurso_tbAlunos1_idx` (`tbAlunos_idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_tbAlunos_has_tbCurso_tbAlunos1`
    FOREIGN KEY (`tbAlunos_idAlunos`)
    REFERENCES `mydb`.`tbAlunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbAlunos_has_tbCurso_tbCurso1`
    FOREIGN KEY (`tbCurso_idCurso`)
    REFERENCES `mydb`.`tbCurso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbExtensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbExtensao` (
  `idExtensao` INT NOT NULL,
  `extNome` VARCHAR(45) NOT NULL,
  `extArea` VARCHAR(45) NOT NULL,
  `extInstituiicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExtensao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbExtensao_has_tbAlunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbExtensao_has_tbAlunos` (
  `tbExtensao_idExtensao` INT NOT NULL,
  `tbAlunos_idAlunos` INT NOT NULL,
  PRIMARY KEY (`tbExtensao_idExtensao`, `tbAlunos_idAlunos`),
  INDEX `fk_tbExtensao_has_tbAlunos_tbAlunos1_idx` (`tbAlunos_idAlunos` ASC) VISIBLE,
  INDEX `fk_tbExtensao_has_tbAlunos_tbExtensao1_idx` (`tbExtensao_idExtensao` ASC) VISIBLE,
  CONSTRAINT `fk_tbExtensao_has_tbAlunos_tbExtensao1`
    FOREIGN KEY (`tbExtensao_idExtensao`)
    REFERENCES `mydb`.`tbExtensao` (`idExtensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbExtensao_has_tbAlunos_tbAlunos1`
    FOREIGN KEY (`tbAlunos_idAlunos`)
    REFERENCES `mydb`.`tbAlunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
